server:
  port: 3001
spring:
  application:
    #eureka集群多个节点的application.name需要配置为一样或者不配置使用默认，否则会出现节点为unavailable-replicas
    name: eureka
eureka:
  instance:
    hostname: peer1
    #prefer-ip-address: true
  client:
    #当搭建高可用服务注册中心集群时下面两项需要true
    #不向注册中心注册自己
    #register-with-eureka: false
    #不从注册中心获取服务列表
    #fetch-registry: false
    service-url:
      #单机 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      defaultZone: http://peer1:3001/eureka/,http://peer2:3002/eureka/
      #defaultZone: http://192.168.2.176:3001/eureka/,http://192.168.2.176:3002/eureka/


#服务监控首页http://peer1:3001/


