server:
  port: 6011
spring:
  application:
    name: provider1
  datasource:
    url: jdbc:mysql://localhost:3306/Test?useSSL=true&verifyServerCertificate=false&characterEncoding=UTF-8
    username: root
    password: wscqtlulu
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  typeAliasesPackage: com.springcloud.provider1.pojo
  mapperLocations: classpath:mapper/*.xml
# 配置集群eureka注册中心
eureka:
  client:
    #仅提供服务，不需要访问其他服务，所以不需要从注册中心获取服务清单
    fetch-registry: false
    service-url:
      defaultZone: http://peer1:3001/eureka/,http://peer2:3002/eureka/
  instance:
    hostname: provider1
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        #此处控制的是不开放哪些端点
        #exclude: shutdown,threaddump
        #此处控制的是开放哪些端点，如果需要开启少数端点可以这样配置：health,info。如果开启多个则使用*号开启除了exclude的端点
        include: "health,info,metrics,beans"
  endpoint:
    health:
      #开放显示health端点详情
      show-details: always
